# Generated by Django 2.1 on 2019-03-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190311_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
