# Generated by Django 2.1 on 2019-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190313_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
