# Generated by Django 2.1 on 2019-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190315_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='end_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='start_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
